# Generated by Django 5.0.3 on 2024-04-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_firends_fidesrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FidesRequest',
        ),
    ]
