# Generated by Django 5.0.3 on 2024-04-04 02:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_fidesrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FidesRequest',
            new_name='FirendRequest',
        ),
    ]
