# Generated by Django 5.0.3 on 2024-04-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirendRequest',
        ),
    ]
